name: PainThermometer
options:
  minimumXcodeGenVersion: 2.42.0
  deploymentTarget:
    watchOS: "8.0"
settings:
  base:
    SWIFT_VERSION: 5.9
    PRODUCT_BUNDLE_IDENTIFIER: dev.startai.PainThermometer
    DEVELOPMENT_TEAM: "A582NTL96F"
targets:
  PainThermometerWatchApp:
    type: application
    platform: watchOS
    sources:
      - PainThermometerWatchApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.startai.PainThermometer.watchkitapp
        INFOPLIST_FILE: PainThermometerWatchApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: PainThermometerWatchApp/PainThermometerWatchApp.entitlements
    dependencies: []
